#!/bin/sh
# @(#) ver 1.0.0 2014.08.31
set -ue

USAGE_EXIT(){
  cat <<++EOS >&2
USAGE:`basename $0` -4 ip_address -f user_flavor [ -s sshkey ] [ -y -P root_password -u default_user -p default_user_password ] jail_name

user_flavor files
    - rc.root   Initial-Script executed by root.
    - rc.local  Initial-Script executed by default_user.
    - pkg.list  Packages for pkg install.
    - ELSE      Copy to new jail.

++EOS
  exit 9
}

readonly DIR=$(dirname `realpath $0`)
readonly PARAMFILE=$DIR/deploy.conf
PREFIX=/usr/jails
NIC=em0
if [ -r $PARAMFILE ]; then
  readonly PARAM_CONTENT=`cat $PARAMFILE`
  tmpval=$(echo "$PARAM_CONTENT" | awk -F"=" '$1 ~ /^PREFIX$/{print $2}')
  if [ "_$tmpval" != "_" ]; then
    PREFIX=$tmpval
  fi
  tmpval=$(echo "$PARAM_CONTENT" | awk -F"=" '$1 ~ /^NIC$/{print $2}')
  if [ "_$tmpval" != "_" ]; then
    NIC=$tmpval
  fi
fi

# get parameters
jail_name=""
ip_address=""
user_flavor=""
sshkey=""
batchmode=0
root_password=""
default_user=""
default_user_password=""
while getopts "4:f:s:yP:u:p:" args
do
  case $args in
    4) ip_address=$OPTARG;;
    f) user_flavor=$OPTARG;;
    s) sshkey=$OPTARG;;
    y) batchmode=1;;
    P) root_password=$OPTARG;;
    u) default_user=$OPTARG;;
    p) default_user_password=$OPTARG;;
    \?) USAGE_EXIT;;
  esac
done
shift $(expr $OPTIND - 1)
if [ $# -eq 0 ]; then
  USAGE_EXIT
fi
jail_name="$1"

# check parameters
if [ "_$ip_address" = "_" -o \
    "_$user_flavor" = "_" -o \
    "_$jail_name" = "_" ]; then
  USAGE_EXIT
fi
if [ $batchmode -eq 1 ]; then
  if [ "_$root_password" = "_" -o \
    "_$default_user" = "_" -o \
    "_$default_user_password" = "_" ]; then
    USAGE_EXIT
  fi
else
  echo -n "Input root password: "
  read root_password
  echo -n "Input default username: "
  read default_user
  echo -n "Input default user password: "
  read default_user_password
fi

# check jails
if qjail list | awk '{print $5}' | grep -x -q "$jail_name" ; then
  echo "existing jail_name: $jail_name"
  exit 9
fi
if qjail list | awk '{print $4}' | grep -x -q "$ip_address" ; then
  echo "existing ip_address: $ip_address"
  exit 9
fi

# confirm
cat <<++EOS

I will create a Jail with the following.
  jail_name :$jail_name
  ip_address :$ip_address
  user_flavor :$user_flavor
  sshkey :$sshkey
  root_password :$root_password
  default_user :$default_user
  default_user_password:$default_user_password

++EOS
if [ $batchmode -eq 0 ] ; then
  echo -n 'create? [y/n]: '
  read YN
  if [ "$YN" != "y" -a "$YN" != "yes" ]; then
    exit 9
  fi
  echo
fi

# create
echo
echo "--- SETUP START ---"

echo "Creating a Jail"
qjail create -n $NIC -4 $ip_address $jail_name
qjail config -k $jail_name

echo
echo "Running initial setting scripts"
for rc_elem in $(find $DIR/rc.init/*.rc); do
  . $rc_elem
done

echo
echo "Starting Jail"
qjail start $jail_name

echo
echo "Setuping users"
echo " setuping root password"
jexec $jail_name sh -c "echo $root_password | pw usermod -n root -h 0"
echo " setuping default_user"
jexec $jail_name sh -c "echo $default_user_password | pw useradd -n $default_user -G wheel -m -h 0"
if [ "_$sshkey" != "_" ]; then
  if [ -f $sshkey ]; then
    echo " cp $sshkey ${PREFIX}/${jail_name}/home/${default_user}/.ssh/authorized_keys"
    jexec -U $default_user $jail_name sh -c "cd /home/${default_user} && mkdir .ssh && chmod 700 .ssh"
    cp $sshkey ${PREFIX}/${jail_name}/home/${default_user}/.ssh/authorized_keys
    jexec $jail_name sh -c "chown ${default_user}:${default_user} /home/${default_user}/.ssh/*"
    jexec -U $default_user $jail_name sh -c "chmod 600 /home/${default_user}/.ssh/*"
  fi
fi

# apply user_flavor
if [ "$user_flavor" != "NONE" ]; then
  echo
  echo "Applying user_flavor"
  cp -vR ${user_flavor}/* ${PREFIX}/${jail_name}/
  jexec $jail_name sh -c "chown -R ${default_user}:${default_user} /home/${default_user}/"
fi

# run scripts
if [ -r ${user_flavor}/pkg.list ] ; then
  echo
  echo "Installing packages"
  jexec $jail_name sh -c 'ASSUME_ALWAYS_YES=yes;cat /pkg.list | xargs pkg install'
fi
if [ -x ${user_flavor}/rc.root ] ; then
  echo
  echo "Running /rc.root"
  jexec $jail_name /rc.root
fi
if [ -x ${user_flavor}/rc.user ] ; then
  echo
  echo "Running /rc.user"
  jexec -U ${default_user} $jail_name /rc.user
fi

echo
echo "--- SETUP END ---"
